# Generated by Django 6.0.6 on 2026-06-21 23:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('quran', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRecitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('evaluation_qualitative', models.CharField(choices=[('excellent', 'Excellent'), ('bien', 'Bien'), ('satisfaisant', 'Satisfaisant'), ('a_revoir', 'À revoir')], max_length=20)),
                ('tajweed_respecte', models.BooleanField(default=False)),
                ('makhraj_correct', models.BooleanField(default=False)),
                ('rythme_adequat', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True)),
                ('date_session', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.classe')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_recitation', to=settings.AUTH_USER_MODEL)),
                ('evaluateur', models.ForeignKey(limit_choices_to={'role': 'enseignant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_donnees', to=settings.AUTH_USER_MODEL)),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quran.surah')),
                ('versets_recites', models.ManyToManyField(blank=True, to='quran.verset')),
            ],
            options={
                'verbose_name': 'Session de Récitation',
                'verbose_name_plural': 'Sessions de Récitation',
                'ordering': ['-date_session'],
            },
        ),
        migrations.CreateModel(
            name='BulletinCoranSenegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('annuel', 'Annuel')], max_length=10)),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('note_memorisation', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('note_recitation', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('note_tajweed', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('note_comprehension', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('appreciation', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.classe')),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to=settings.AUTH_USER_MODEL)),
                ('sourates_validees', models.ManyToManyField(blank=True, related_name='bulletins', to='quran.surah')),
            ],
            options={
                'verbose_name': 'Bulletin Coranique',
                'verbose_name_plural': 'Bulletins Coraniques',
                'unique_together': {('eleve', 'classe', 'periode', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='ProgressionMemorisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('non_commence', 'Non commencé'), ('en_cours', 'En cours'), ('memorise', 'Mémorisé'), ('maitrise', 'Maîtrisé')], default='non_commence', max_length=15)),
                ('versets_memorises', models.PositiveSmallIntegerField(default=0)),
                ('note_recitation', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('commentaire_enseignant', models.TextField(blank=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_maitrise', models.DateField(blank=True, null=True)),
                ('derniere_evaluation', models.DateTimeField(blank=True, null=True)),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to=settings.AUTH_USER_MODEL)),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='quran.surah')),
            ],
            options={
                'verbose_name': 'Progression Mémorisation',
                'verbose_name_plural': 'Progressions Mémorisation',
                'ordering': ['-derniere_evaluation'],
                'unique_together': {('eleve', 'surah')},
            },
        ),
    ]
