# Generated by Django 6.0.6 on 2026-06-21 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('quran', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_quiz', models.CharField(choices=[('memorisation', 'Test de Mémorisation'), ('comprehension', 'Test de Compréhension'), ('tajweed', 'Règles de Tajweed'), ('general', 'Évaluation Générale')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('duree_minutes', models.PositiveSmallIntegerField(default=30)),
                ('note_maximale', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('actif', models.BooleanField(default=True)),
                ('date_debut', models.DateTimeField(blank=True, null=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('classes', models.ManyToManyField(blank=True, related_name='quiz', to='accounts.classe')),
                ('createur', models.ForeignKey(limit_choices_to={'role': 'enseignant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_crees', to=settings.AUTH_USER_MODEL)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='curriculum.niveauscolaire')),
                ('surah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz', to='quran.surah')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quiz',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_question', models.CharField(choices=[('qcm', 'Choix Multiple (QCM)'), ('vf', 'Vrai ou Faux'), ('texte_lacunaire', 'Texte à Trous'), ('reponse_libre', 'Réponse Libre')], max_length=20)),
                ('enonce', models.TextField()),
                ('enonce_arabe', models.TextField(blank=True)),
                ('points', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('explication', models.TextField(blank=True, help_text='Explication de la bonne réponse')),
                ('ordre', models.PositiveSmallIntegerField(default=1)),
                ('verset_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_quiz', to='quran.verset')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['quiz', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='ReponseQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('texte_arabe', models.TextField(blank=True)),
                ('est_correcte', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='quiz.question')),
            ],
            options={
                'verbose_name': 'Réponse',
                'verbose_name_plural': 'Réponses',
            },
        ),
        migrations.CreateModel(
            name='TentativeQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('soumis', 'Soumis'), ('evalue', 'Évalué')], default='en_cours', max_length=10)),
                ('note_obtenue', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('eleve', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'Tentative de Quiz',
                'verbose_name_plural': 'Tentatives de Quiz',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ReponseEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_texte', models.TextField(blank=True)),
                ('est_correcte', models.BooleanField(blank=True, null=True)),
                ('points_obtenus', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.question')),
                ('reponse_choisie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quiz.reponsequestion')),
                ('tentative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_eleve', to='quiz.tentativequiz')),
            ],
            options={
                'verbose_name': 'Réponse Élève',
                'verbose_name_plural': 'Réponses Élèves',
                'unique_together': {('tentative', 'question')},
            },
        ),
    ]
