# Generated by Django 6.0.6 on 2026-06-21 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True)),
                ('nom_arabe', models.CharField(max_length=100)),
                ('nom_translittere', models.CharField(max_length=100)),
                ('nom_francais', models.CharField(max_length=100)),
                ('nombre_versets', models.PositiveSmallIntegerField()),
                ('type_revelation', models.CharField(choices=[('mecquoise', 'Mecquoise'), ('medinoise', 'Médinoise')], max_length=15)),
                ('ordre_revelation', models.PositiveSmallIntegerField()),
                ('description_fr', models.TextField(blank=True, help_text='Description pédagogique en français')),
                ('audio_url', models.URLField(blank=True)),
                ('niveau_difficulte', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1, help_text='1 = Facile (pour CI/CP), 5 = Difficile (pour Terminale)')),
            ],
            options={
                'verbose_name': 'Sourate',
                'verbose_name_plural': 'Sourates',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Tajweed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie', models.CharField(choices=[('makhraj', "Makhraj (Point d'articulation)"), ('sifat', 'Sifat (Caractéristiques)'), ('madd', 'Madd (Prolongation)'), ('waqf', 'Waqf (Arrêt)'), ('idgham', 'Idgham (Assimilation)'), ('ikhfa', 'Ikhfa (Occultation)'), ('iqlab', 'Iqlab (Changement)')], max_length=20)),
                ('description_fr', models.TextField()),
                ('exemple_arabe', models.CharField(blank=True, max_length=200)),
                ('niveau_scolaire', models.CharField(blank=True, help_text='Niveau scolaire recommandé pour introduire cette règle', max_length=20)),
            ],
            options={
                'verbose_name': 'Règle de Tajweed',
                'verbose_name_plural': 'Règles de Tajweed',
            },
        ),
        migrations.CreateModel(
            name='Verset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('texte_arabe', models.TextField()),
                ('translitteration', models.TextField(blank=True)),
                ('traduction_fr', models.TextField(blank=True)),
                ('traduction_wolof', models.TextField(blank=True)),
                ('notes_pedagogiques', models.TextField(blank=True)),
                ('audio_url', models.URLField(blank=True)),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versets', to='quran.surah')),
            ],
            options={
                'verbose_name': 'Verset',
                'verbose_name_plural': 'Versets',
                'ordering': ['surah', 'numero'],
                'unique_together': {('surah', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='GlossaireIslamique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terme_arabe', models.CharField(max_length=100)),
                ('terme_francais', models.CharField(max_length=100)),
                ('terme_wolof', models.CharField(blank=True, max_length=100)),
                ('definition_fr', models.TextField()),
                ('exemple_utilisation', models.TextField(blank=True)),
                ('verset_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glossaire', to='quran.verset')),
            ],
            options={
                'verbose_name': 'Terme du Glossaire',
                'verbose_name_plural': 'Glossaire Islamique',
                'ordering': ['terme_francais'],
            },
        ),
    ]
