# Generated by Django 6.0.6 on 2026-06-21 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quran', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NiveauScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('cycle', models.CharField(choices=[('primaire', 'Enseignement Primaire'), ('moyen', 'Enseignement Moyen (Collège)'), ('secondaire', 'Enseignement Secondaire (Lycée)')], max_length=20)),
                ('ordre', models.PositiveSmallIntegerField(help_text='Ordre dans la progression scolaire')),
                ('description', models.TextField(blank=True)),
                ('competences_cibles', models.TextField(blank=True, help_text='Compétences visées pour ce niveau')),
            ],
            options={
                'verbose_name': 'Niveau Scolaire',
                'verbose_name_plural': 'Niveaux Scolaires',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='PlanDeLecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('duree_minutes', models.PositiveSmallIntegerField(default=60)),
                ('objectifs', models.TextField()),
                ('prerequis', models.TextField(blank=True)),
                ('deroulement', models.TextField(help_text='Déroulement détaillé de la séance')),
                ('activites_eleves', models.TextField(blank=True)),
                ('evaluation', models.TextField(blank=True)),
                ('materiel_requis', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('valide', 'Validé'), ('archive', 'Archivé')], default='brouillon', max_length=15)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(limit_choices_to={'role': 'enseignant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_lecon', to='curriculum.niveauscolaire')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans_lecon', to='quran.surah')),
                ('versets', models.ManyToManyField(blank=True, related_name='plans_lecon', to='quran.verset')),
            ],
            options={
                'verbose_name': 'Plan de Leçon',
                'verbose_name_plural': 'Plans de Leçons',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeCoranSenegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectifs_generaux', models.TextField()),
                ('heures_hebdomadaires', models.DecimalField(decimal_places=1, default=2.0, max_digits=4)),
                ('annee_scolaire', models.CharField(default='2024-2025', max_length=9)),
                ('niveau', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='programme', to='curriculum.niveauscolaire')),
                ('regles_tajweed', models.ManyToManyField(blank=True, related_name='programmes', to='quran.tajweed')),
            ],
            options={
                'verbose_name': 'Programme Coranique',
                'verbose_name_plural': 'Programmes Coraniques',
            },
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type_ressource', models.CharField(choices=[('audio', 'Fichier Audio'), ('video', 'Vidéo'), ('pdf', 'Document PDF'), ('image', 'Image'), ('lien', 'Lien externe')], max_length=10)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='ressources/')),
                ('url_externe', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('niveau', models.ManyToManyField(blank=True, related_name='ressources', to='curriculum.niveauscolaire')),
                ('plan_lecon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources', to='curriculum.plandelecon')),
                ('surah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ressources', to='quran.surah')),
            ],
            options={
                'verbose_name': 'Ressource Pédagogique',
                'verbose_name_plural': 'Ressources Pédagogiques',
            },
        ),
        migrations.CreateModel(
            name='SourateParNiveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode', models.CharField(choices=[('S1', 'Semestre 1'), ('S2', 'Semestre 2'), ('annee', "Toute l'année")], default='annee', max_length=10)),
                ('versets_debut', models.PositiveSmallIntegerField(default=1)),
                ('versets_fin', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('obligatoire', models.BooleanField(default=True)),
                ('ordre_enseignement', models.PositiveSmallIntegerField(default=1)),
                ('notes_enseignant', models.TextField(blank=True)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curriculum.programmecoransenegal')),
                ('surah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quran.surah')),
            ],
            options={
                'verbose_name': 'Sourate par Niveau',
                'verbose_name_plural': 'Sourates par Niveau',
                'ordering': ['ordre_enseignement'],
            },
        ),
        migrations.AddField(
            model_name='programmecoransenegal',
            name='sourates_a_memoriser',
            field=models.ManyToManyField(related_name='programmes', through='curriculum.SourateParNiveau', to='quran.surah'),
        ),
    ]
